- topic_name: /camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: ignition.msgs.Image
- topic_name: /camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: ignition.msgs.CameraInfo
- topic_name: /world/empty/pose/info
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
# - topic_name: /clock
#   ros_type_name: rosgraph_msgs/msg/Clock
#   gz_type_name: ignition.msgs.Clock
#   direction: GZ_TO_ROS
