trajectory:
  joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  points:
    - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      time_from_start:
        sec: 1
        nanosec: 0
    - positions: [1.0, 0.5, 0.0, -0.5, 0.0, 0.0]
      time_from_start:
        sec: 3
        nanosec: 0
